version: '3.2'

networks:
  sinnet:
    name: sinnet

services:
  mysql-db:
    build: ./mysql
    container_name: sin-mysql
    networks:
      - "sinnet"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/etc/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/etc/mysql.conf.d:/etc/mysql/mysql.conf.d:ro
      - ./mysql/log:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    command: "--character-set-server=utf8"

  redis-db:
     build: ./redis
     container_name: sin-redis
     networks:
       - "sinnet"
     ports:
       - "6379:6379"
     volumes:
       - ./redis/etc:/usr/local/etc/redis:ro
       - ./redis/data:/data:rw
     restart: always

  php-fpm:
    build: ./php/72
    container_name: sin-php
    networks:
      - "sinnet"
    ports:
      - "9000:9000"
    stdin_open: true
    tty: true
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    volumes:
      #- /data/web:/usr/local/apache2/htdocs:rw
      - /data/web:/var/www/html:rw
      - ./php/72/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/72/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./php/72/etc/php-fpm.d:/usr/local/etc/php-fpm.d:ro
      - ./php/log/php-fpm:/var/log/php-fpm:rw
    restart: always
    command: php-fpm

  nginx:
    build: ./nginx
    container_name: sin-nginx
    networks:
      - "sinnet"
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - /data/web:/var/www/html:rw
      - ./nginx/etc/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
      #- "443:443"
    restart: always
    command: nginx -g 'daemon off;'
